# name: A workflow for my Hello World file
# on: push

# jobs:
#   build:
#     name: Hello world action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cat CODEOWNERS
#         name: hot sauce
      
on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: job name
        if: github.event.review.state == 'approved'
        run: |
          echo "Job=$(${{ github.event.pull_request.node_id }})" >> $env:GITHUB_ENV
      - name: SaveName
        run: echo ${{ env.Job }}
