# name: A workflow for my Hello World file
# on: push

# jobs:
#   build:
#     name: Hello world action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cat CODEOWNERS
#         name: hot sauce
      
on:
  discussion_comment:
    types: [created, deleted]
  # pull_request:
  #   branches:
  #     - main
  # pull_request_review:
  #   types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: job name
        #if: github.event.review.state == 'approved'
        run: |
          touch .job
          echo JOB =${{ github.event.pull_request.node_id }} >> .job
      - name: pring  
        run: |
          cat .job

